version: '3'
services: 
  db:
    container_name: postgres_container
    image: postgres:12
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: W0rkW1thSQL
      POSTGRES_DB: prod_db
    volumes: 
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always 
  client:
    build: "./client"
    ports: 
      - "80:80"
  gateway: 
    build: "./server/gateway"
    ports: 
      - "8080:8080"
    depends_on: 
      - auth
      - projects
  auth:
    build: "./server/auth"
    restart: always
    ports: 
      - "3000:3000"
    depends_on: 
      - db
    environment: 
      JWT_SECRET: test_task
      JWT_SECRET_REFRESH: token_refresh
      JWT_EXPIRES_IN: 3600000
      JWT_REFRESH_EXPIRES_IN: 864000000
      JWT_ACC_ACTIVATE: activate_account
      MAIL_NAME: Test Task Notifications
      MAIL_SECRET: secret-mail
      SMTP_USERNAME: test.acc0unt.sendmail@gmail.com
      SMTP_PASSWORD: test_pass_for_sending
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
  projects:
    build: "./server/projects"
    ports: 
      - "3001:3001"
    environment:
      JWT_SECRET: test_task
      JWT_SECRET_REFRESH: token_refresh
      JWT_EXPIRES_IN: 60400000
      JWT_REFRESH_EXPIRES_IN: 864000000
    depends_on: 
      - db
      - auth