version: '3'
services: 
  db:
    image: postgres:12
    env_file: 
      - database.env
    volumes: 
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always 
  client:
    build: 
      dockerfile: Dockerfile
      context: ./client
    environment:
      IP_ADDRESS: "79.143.29.80"
    ports: 
      - "80:80"
  gateway: 
    build: "./server/gateway"
    ports: 
      - "8080:8080"
  auth:
    build: "./server/auth"
    restart: always
    ports: 
      - "4000:4000"
    depends_on: 
      - db
    env_file: 
      - './server/auth/.env'
  projects:
    build: "./server/projects"
    ports: 
      - "4001:4001"
    env_file:
      - './server/projects/.env'
    depends_on: 
      - db